import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 844 } });
const errs = [];
p.on('pageerror', e => errs.push('PAGEERROR ' + e.message));
p.on('console', m => { if (m.type() === 'error') errs.push('CONSOLE ' + m.text()); });
const reqs = [];
p.on('requestfailed', r => reqs.push('FAILED ' + r.url()));
await p.goto('http://localhost:3211/yahtzee/');
await p.waitForTimeout(700);
console.log('setup', await p.getByTestId('setup').isVisible());
await p.getByLabel('Player name', {exact:true}).fill('Ana');
await p.getByTestId('add-player').click();
await p.getByTestId('start-game').click();
console.log('game', await p.getByTestId('game').isVisible());
await p.evaluate(() => { window.__yahtzeeDice = [6,6,6,6,6]; });
await p.getByTestId('roll').click();
await p.waitForTimeout(400);
console.log('yahtzee value', await p.getByTestId('score-yahtzee').getByTestId('score-value').textContent());
console.log('sw registered', await p.evaluate(() => navigator.serviceWorker.getRegistrations().then(r => r.length)));
console.log('manifest url', await p.evaluate(() => document.querySelector('link[rel=manifest]')?.href));
await p.reload();
await p.waitForTimeout(400);
console.log('after reload current', await p.getByTestId('current-player').textContent());
console.log('issues', [...new Set(errs.concat(reqs))]);
await b.close();
